### ISSUE TITLE
withAPIData is now deprecated, possible fix using withSelect

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/inhabitent-blocks#1]
The easiest solution is to use the Gutenberg Cover block which does the same thing.

http://gutenberghub.com/cover-image-block-overview-how-to-use-guide/

https://github.com/redacademy/inhabitent-blocks/blob/1f2291b33a65495bd2daee56d3714c1d6bcbd55c/src/hero-image-header/block.js#L14

zgordon has a similar fix which I was looking into: https://github.com/zgordon/gutenberg-course/blob/master/blocks/12-dynamic/index.js

For now we will need to use an older version of Gutenberg to avoid issues: https://wordpress.org/plugins/gutenberg/advanced/ select and download 3.5.0

**Comment by aswistowska** [comment]
https://github.com/redacademy/inhabitent-blocks/pull/2
